ServerEvents.recipes(event => {
    event.recipes.create.milling(Item.of('kubejs:quartz_seed', 3), Item.of('minecraft:quartz'))
    event.recipes.create.milling(Item.of('kubejs:redstone_seed', 3), Item.of('create:rose_quartz'))
    event.recipes.create.milling(Item.of('kubejs:certus_quartz_seed', 3), Item.of('ae2:certus_quartz_crystal'))
    event.recipes.create.milling(Item.of('kubejs:rune_dust', 4), Item.of('forbidden_arcanus:rune'))
    event.recipes.create.milling(Item.of('kubejs:powdered_flint'), Item.of('minecraft:flint'))
    event.recipes.create.milling(Item.of('minecraft:gravel'), Item.of('minecraft:mossy_cobblestone'))
    event.recipes.create.cutting(Item.of('ae2:certus_quartz_dust'), Item.of('ae2:certus_quartz_crystal'))
    event.recipes.create.milling(Item.of('minecraft:sand').withChance(0.33), Item.of('minecraft:gravel'))
    event.recipes.create.milling([Item.of('create:powdered_obsidian'), Item.of('create:powdered_obsidian').withChance(0.50)], Item.of('minecraft:obsidian')).processingTime(200)
    event.recipes.create.milling(Item.of('thermal:blizz_powder', 3), Item.of('thermal:blizz_rod'))
    event.recipes.create.milling(Item.of('thermal:basalz_powder', 3), Item.of('thermal:basalz_rod'))
    event.recipes.create.milling(Item.of('thermal:blitz_powder', 3), Item.of('thermal:blitz_rod'))
})